spring:
  datasource:
    url: jdbc:postgresql://squad02-osmochilas-rds.cvpksv55zfzp.us-east-1.rds.amazonaws.com:5432/postgres?user=postgres&password=OsMochilas321
  jpa:
#    hibernate:
#      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect

springdoc:
  api-docs:
    path: /api-docs